### ISSUE TITLE
Player Tag Bug?

### ISSUE THREAD

**Issue by resepignev** [Avicus/Issues#622] opened 2015-08-22 19:31 UTC
I don't know how to call it, but if you are on one of the 1.8 servers (dtm01/ctw01) Player tags are following you. Apparently it the first name in the tab list.
I have a Video that's uploading right now and screenshots.
It only happens in 1.8 and on Avicus.
Video: http://youtu.be/7zSYZPbgrH4
Screenshots: 
![2015-08-22_21 11 07](https://cloud.githubusercontent.com/assets/8640683/9425578/77ffa53e-4915-11e5-88a7-ec5ab087939e.png)
![2015-08-22_21 00 44](https://cloud.githubusercontent.com/assets/8640683/9425579/7eba64fe-4915-11e5-8a87-e884456359e3.png)
![2015-08-22_21 04 37](https://cloud.githubusercontent.com/assets/8640683/9425580/8ddc1af4-4915-11e5-983d-0ef016d93b01.png)

**Comment by Aki35** [comment] 2015-08-22 19:58
I had the same issue yesterday as well.

**Comment by keenanthompson** [comment] 2015-08-23 02:58
Can you reproduce this on the full 1.8 server (ip: **1.8.avic.us**)

**Comment by resepignev** [comment] 2015-08-23 19:26
I'll try my best, but it happened on the full 1.8 server too, I'll try to get evidence

**Comment by keenanthompson** [comment] 2015-08-23 20:11
I'm talking with that specific IP, 1.8.avic.us. I can't guarantee things will work perfectly with the 1.7/1.8 support server (avic.us).

**Comment by resepignev** [comment] 2015-08-24 12:02
Yup still happened with 1.8.avic.us on DTM01.
Video: http://youtu.be/TJiABNUKinU

**Comment by keenanthompson** [comment] 2015-08-25 16:38
So it occurs occasionally, correct? You just join a server and it happens sometimes.

**Comment by resepignev** [comment] 2015-08-25 16:42
Correct

**Comment by AustinLMayes** [comment] 2015-08-25 23:07
It occurs when the top player in the tab list joins after you. (You have to be able to see them when they join)

**Comment by steven5703** [comment] 2015-08-28 16:38
I think it also happens because of the anti cheat's kill aura detector,
like if it detects that your head snaps and hits the "fake" player floating
around your head it sends a report. Another thing I noticed is that there
is sometimes 2 player tags with no body to the left and right of you, or
sometimes above you there is a full player with a body and a white name tag

**Comment by keenanthompson** [comment] 2015-08-28 17:03
We'll look into that @steven5703

**Comment by javipepe** [comment] 2015-11-08 13:50
Does this still happen? @steven5703 @resepignev @Aki35 @AustinLMayes

**Comment by ParaSpider** [comment] 2015-11-08 18:00
@javipepe Yes

**Comment by thekeenant** [comment] 2016-02-08 18:07
Fixed with AAC removal.

**Closed by thekeenant** 2016-02-08 18:07 UTC
Labels: plugin
