### ISSUE TITLE
team page

### ISSUE THREAD

**Issue by devrevs** [Avicus/Issues#1272] opened 2017-07-20 01:42 UTC
whenever I try and edit my teams about page I get 505 error
An error was encountered during the request. 
Exception ID: DXHJICZJ

**Comment by benrobson** [comment] 2017-07-27 01:34
@devrevs what exactly are you trying to do?

**Comment by shadowolfyt** [comment] 2017-07-27 01:42
@AustinLMayes I know you're active here, close this please.

**Comment by tnws** [comment] 2017-09-20 19:16
I can't reproduce this locally or on the server, going to close this

**Closed as completed by tnws** 2017-09-20 19:16 UTC
Labels: website
