### ISSUE TITLE
Specator name tag glitch (1.8 servers)

### ISSUE THREAD

**Issue by TheAwesomeApricot** [Avicus/Issues#623] opened 2015-08-23 17:04 UTC
Whilst on a 1.8 server, when in game on a team, name tags will float around you to your left, right and above. These names are of players either spectating or have previously spectated, and is extremely annoying as it seems as if someone is beside you at all times.

**Comment by TheAwesomeApricot** [comment] 2015-08-23 17:07
![2015-08-22_15 13 41](https://cloud.githubusercontent.com/assets/7271809/9429247/aded66c0-49c1-11e5-952d-20305de148f0.png)
![2015-08-22_15 13 44](https://cloud.githubusercontent.com/assets/7271809/9429249/b5185266-49c1-11e5-8d7b-46144586fa37.png)
![2015-08-22_15 15 31](https://cloud.githubusercontent.com/assets/7271809/9429250/c038b776-49c1-11e5-9cb4-745acef6f863.png)

**Comment by TheAwesomeApricot** [comment] 2015-08-23 17:07
after looking at my pictures, I see I wasn't in game, but it does happen i game too.

**Comment by AustinLMayes** [comment] 2015-08-23 18:16
Dupe of #622

**Comment by keenanthompson** [comment] 2015-08-23 20:10
Report at #622

**Closed by keenanthompson** 2015-08-23 20:10 UTC
