### ISSUE TITLE
Staff with worldedit can't use wooden axes in-game

### ISSUE THREAD

**Issue by Palmidence** [Avicus/Issues#798] opened 2016-08-19 19:46 UTC
It's a disadvantage for me, it'd be nice if we could use wooden axes (I need them for defense and not all maps have different materials)

**Comment by AustinLMayes** [comment] 2016-08-23 09:56
Fixed in Atlas

**Comment by thekeenant** [comment] 2016-08-23 13:03
I don't see how this is fixed in atlas? @austinlmayes

**Comment by thekeenant** [comment] 2016-08-23 13:04
@palmidence I don't think you should have world edit perms, different issue though.

**Comment by ProfessorUtonium** [comment] 2016-08-23 13:07
It's the mapdev rank

they have WE perms

**Comment by ProfessorUtonium** [comment] 2016-08-23 13:17
@palmidence /toggleeditwand can disable it. You need to do this on every server though (such as once on throwback and once on CTW)

And @thekeenant refer to my response above for the issue

**Comment by thekeenant** [comment] 2016-08-23 13:21
That's a good fix, we can't do much about it.

**Closed by thekeenant** 2016-08-23 13:21 UTC

**Comment by AustinLMayes** [comment] 2016-08-23 17:07
@thekeenant Right now we remove all WE perms on join, we remove less perms in Atlas

**Comment by thekeenant** [comment] 2016-08-23 19:22
The problem isn't that they cannot use WorldEdit in game, it's that they can @AustinLMayes :stuck_out_tongue:

**Comment by AustinLMayes** [comment] 2016-08-23 23:02
@thekeenant I think the original issue is that they can't use it in game.
